---
title: "**Neuropsychological profile of Unipolar Major Depression with psychotic features:** protocol for a systematic review and bayesian meta-analysis"
author: |
  | Natália Canário$^a$
  | Breno Souza-Marques$^a$$^b$
  | Aline S. Sampaio$^a$$^b$
  | Lucas C. Quarantini$^a$$^b$^[Corresponding author: Lucas C. Quarantini lcq@ufba.br]
  |
  | $^a$Laboratory of Neuropsychopharmacology, Federal University of Bahia
  | $^b$Graduate Program in Medicine and Health, Federal University of Bahia
abstract: This is a protocol for a systematic review with meta-analysis. This systematic review is focused on summarizing, and critically assessing, the available evidence both *for* and *against* a neuropsychological endophenotype of individuals with psychotic major depressive disorder. To this end, we will conduct a systematic appraisal of the literature, followed by a Bayesian meta-analysis and meta-regression. We follow the PRISMA-P guidelines for systematic review protocols [@shamseerPreferredReportingItems2015].
output: 
    bookdown::pdf_document2:
      toc: FALSE
      number_sections: TRUE
classoption:
  - onecolumn
geometry: "left=2.5cm, right=2.5cm, top=2cm, bottom=2cm"
fontsize: 12pt
bibliography: mylib.bib
link-citations: yes
csl: apa.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```
# Rationale

Unipolar major depression with psychotic features (PMDD) is characterized by the presence of unipolar major depressive disorder (MDD), concomitant with hallucinations and/or delusional beliefs. PMDD is generally seen as a worse kind of MDD, with a profile of symptoms thought to lie between MDD and more severe psychotic disorders such as schizophrenia [@dubovskyPsychoticDepressionDiagnosis2021; @ostergaardMeasuringPsychoticDepression2014]. This is reflected on previous editions of the Diagnostic and Statistical Manual of Mental Disorders [@apaDiagnosticStatisticalManual2013], where PMDD was classified as an impaired sub-type of depression. 

The available evidence, however, has shown that individuals with MDD may exhibit a more severe case of depression than those with PMDD [@parkPsychoticDepressionAssessment2014; @ostergaardValiditySeverityPsychosis2012], suggesting that a "severity approach" to PMDD may not be as precise as previously thought. These findings blur the line between diagnoses from a symptom severity point-of-view, thus, a search for an endophenotype of these disorders, beyond assessing how severe are the depressive symptoms of an individual, may offer a clearer picture that helps define the boundaries and develop interventions tailored to the differences between PMDD and MDD.

## Neuropsychological profiles of PMDD: evidence from meta-analytic studies

The debate on whether there is a specific neuropsychological endophenotype for unipolar major depressive disorder with psychotic features, that is different from both non-psychotic unipolar depression (MDD) and schizophrenia, is not new [@jesteClinicalNeuropsychologicalComparison1996]. The number of studies has only recently increased enough to allow a more systematic and robust assessment of the evidence. Thus, efforts to summarize the available evidence on neuropsychological performance of individuals with PMDD are still scarce [@flemingNeuropsychologicalCorrelatesPsychotic2004; @zaninottoCognitiveMarkersPsychotic2015; @vermeulenCognitiveDeficitsOlder2019]. The study by @flemingNeuropsychologicalCorrelatesPsychotic2004 focused on whether neuropsychological tests could help differentiate individuals with PMDD from others with MDD, but due to the small number of studies available at the time (only five), some cognitive functions were compared in a very limited pool of data, sometimes only between two samples.

The review by Zaninotto et al. (2015) was able to include 12 studies. They found significant effects of standardized mean difference (SMD) = -0.67 [95%CI: -0.82, -0.52] for Verbal memory (*n* of studies = 6), SMD = -0.62 [95%%CI: -0.80, -0.44] for Visual memory (*n* of studies = 4), and SMD = -0.74 [95%CI: -0.88, -0.59] for Processing Speed (*n* of studies = 8), but not for Attention and Reasoning domains. For a measure of global cognition computed by the study authors, a significant effect of SMD = - 0.38 [95%CI: -0.57, -0.19] was observed. It is important to note that authors excluded two of the studies they found to be outliers for this latter analysis, and six out of the ten studies had confidence intervals crossing zero. Finally, authors assessed age, gender, education and depressive symptoms severity as single moderators, finding an effect for age ($\beta$ = -1.31, SE = 0.5, p = 0.01) in working memory tasks, but not for the other moderators.

The latest study to assess neuropsychological performance differences between PMDD and MDD individuals focused on older patients [@vermeulenCognitiveDeficitsOlder2019]. Authors included a total of 7 studies, and 3 of those had patients with bipolar psychotic depression. They found a SMD of -0.26 for measures of global cognition [95%CI -0.49, -0.02], SMD = -0.64 [95%CI: -1.24, -0.03] for Attention (*n* of studies = 5), SMD = -0.43 [95%CI: -0,69, -0,17] for Executive Function (*n* of studies = 6), and SMD = -0.43 [95%CI: -0.70, -0.17] for Memory (*n* of studies = 5), but no significant effect for Verbal fluency.

This brief review of the current evidence for a neuropsychological endophenotype that can differentiate PMDD from MDD patients shows that the meta-analytic studies conducted so far faced some critical limitations. High heterogeneity and a small number of studies can impede researchers from clearly establishing a consistent and robust assessment of the reported effects. More importantly, results vary between meta-analytic studies over which neuropsychological functions are more significantly impaired in individuals with PMDD in comparison with MDD subjects. This means that non-significant *p*-values may have been taken as evidence of an absence of effect, when they may simply be an absence of evidence in face of the above mentioned limitations [@nickersonNullHypothesisSignificance2000; @dienesUsingBayesGet2014; @altmanStatisticsNotesAbsence1995a].

# Objectives

In this systematic review with meta-analysis, we examine the available literature to answer the following questions:

 - Q1: *"**Is there a neuropsychological profile (an endophenotype) for major depressive disorders with psychotic features that is different from that of non-psychotic unipolar depression?**"*
 For this question, we define a neuropsychological profile as a combination of results that quantify the difference in performance between individuals with PMDD and MDD, and that reflects an established neuropsychological function or domain of interest.

 - Q2: *"**What are the moderators that can influence this neuropsychological profile?**"*
 For this question, we define moderators in three broad categories: within-subject clinical factors (age, acute psychotic episode, psychiatric comorbidities, number of hospitalizations, severity of depressive symptoms, years with diagnosis, family members with psychiatric conditions, and other relevant information); within-subject sociodemographical variables (years of education, household income, marital status, employment status); and between-study factors (study design and setting, type of neuropsychological tests used).
 
We set out to answer these questions with a Bayesian meta-analysis and meta-regression. New variables of interest may be included if found to help better understand the available evidence. A critical, qualitative appraisal of the literature is also warranted, and should help to identify current gaps, inconsistencies and limitations of relevant studies.

# Methods

This systematic review has been registered at the PROSPERO (código do registro aqui) database for systematic reviews. The following information is also available at (LINK DO PROSPERO).

## Eligibility criteria

In this review, we focus on major depressive disorder with psychotic features. Eligible studies must include patients with this diagnosis who underwent a cognitive assessment of an established neuropsychological domain.

### Types of studies

We include studies with a quantitative approach, which measure neuropsychological performance with standardized tests and tasks. To allow for an estimation of differences, subjects with PMDD must be compared to a sample of patients with MDD or other psychotic disorders, such as schizophrenia and psychotic bipolar depression.

### Exclusion Criteria

### Data Extraction

#### Measures of effect size

#### Moderators

## Using a bayesian meta-analysis to assess the available evidence

A fully bayesian framework may offer significant advantages over a frequentist method given the previously discussed limitations in the available literature. The small number of studies at the time of these meta-analyses may have ruled out smaller but meaningful effects between PMDD and MDD groups on the basis of a non-significant *p*-value. In addition, use of the Bayes Factor [@wagenmakersBayesianHypothesisTesting2010] allows for the assessment of the available evidence both *for* and *against* an effect (i.e., evidence for the null hypothesis) between individuals with PMDD and MDD. These advantages extend to the use of bayesian meta-regression (hierarchical random-effects models) to measure the possible clinical and sociodemographical moderators. In sum, a fully bayesian framework offers a clearer picture of current evidence, and helps establish to which extent results support a neuropsychological endophenotype for individuals with PMDD.

## Bayesian Location-Scale Meta-Analysis

A bayesian location-scale meta-analysis will be conducted using the r package `blsmeta` [@williamsPuttingVariationVariance2021].

### Bayesian Meta-Regression: Hierarchical Mixed-Effects Models

Meta-Regression is a statistical tool to assess the effects of pooled study-level factors, such as age, gender and psychiatric comorbidity. In this systematic review, we will focus on possible effects of VARIÁVEIS to be assessed by a Bayesian Hierarchical Model run on the `blsmeta` package.

### Between-study variance ($\tau^2$)




\newpage
# References